my自用


hostname =  www.guazimanhua.com

# 瓜子漫画
^https?:\/\/www\.guazimanhua\.com\/chapter\.php url response-body (<head\b[^>]*>) response-body $1<style>div.desktop-reader-top-ad,div.mobile-reader-top-static-ad,div[aria-label="推广"],div[aria-label="广告"]{display:none!important;}</style>